### ISSUE TITLE
Can't escape the x-ray view

### ISSUE THREAD

**Issue by nallath** [fieldOfView/Cura-MeshTools#4]
It's one of those issues that is best solved on both ends of the spectrum.

If you load a non watertight model in 4.0 (https://www.thingiverse.com/thing:3505006) and you have the mesh tools plugin installed, you're asked if you want to inspect the model in x-ray view. But this view change doesn't also change the stage to prepare, so there is no way to leave the x-ray view in 4.0.0 (since there is no way to select solid view anymore).

Depending on how you feel about this, I guess we should change that switching to Prepare forces the view to prepare (so that switching back & forth at least puts you back in a workable state). Since we can't realy change anything for a version that's out there (and plugins can adapt & overcome), it might also be a good idea to fix this from the plugins side (eg; switch stage first and then set the view).

**Comment by fieldOfView** [comment]
The problem does not reproduce with the version I just downloaded from the Marketplace on Cura 4.0.0. Cura switches to the Preview stage when pressing the Show X-Ray button(*).

Are you sure you are using the version that is currently in the Marketplace? I remember fixing this issue here: https://github.com/fieldOfView/Cura-MeshTools/commit/7185c76519b1a2dfe8b6271d89279b612b48cf6d

*: The X-Ray view has no business being in the Preview stage. It makes no sense whatsoever to go layer view first to then switch to a view that highlights problems that should have been fixed *before* slicing. That's why I moved it to the Prepare stage in my Sidebar GUI plugin. But that is very off-topic here.

**Comment by nallath** [comment]
Yup. It was the version I downloaded from the marketplace. But I'm running it from source, so it could very well be that that caused some of the issues. 

I agree with the weird location of the x-ray view, but it wasn't my call to make.

**Comment by fieldOfView** [comment]
I assume you are running the master branch? I'm testing with the 4.0 branch, and it works there (whether from source or with the frozen version).

**Comment by nallath** [comment]
I haven't tested the 4.0 branch yes, so it could be that something got messed up along the way. 

Hmz, can't seem to be able to reproduce it anymore.
